### ISSUE TITLE
function sendmail send with SMTP ?

### ISSUE THREAD

**Issue by leohmoraes** [Prescia/Prescia#1]
Some servers prevented the use of the MAIL command, being necessary to authenticate and send messages via SMTP.

**Comment by Prescia** [comment]
This is probably a server that is not properly configured, because old/obsolete installs of PHP had some exploits on the mail function and sysAdmins decided to disable it. Now the mail function have better parameters to protect it (-f and -a), which are used by Prescia. Check with the server PHP configurations to allow the use of the mail function as long as the PHP version is 5.4+

Otherwise you will need to implement a smtp function. There is a POP function (not in use) inside the library, but a SMTP function was never implemented. Also, to use a smtp function raw, you need permission to use fopen() or fsocket(), and a server that blocks mail() probably blocks those two ... so your best chances would be searching a solution with CURL or something.
